In [1]:
import numpy as np

In [2]:
data_dir = '/Users/lexijones/Dropbox (MIT)/Grad_School/2021_Summer_UROP/data/'
data_file = 'SOCAT_data_North_Pacific.csv'

In [9]:
SOCAT = np.genfromtxt(data_dir + data_file,delimiter=',')

In [10]:
np.shape(SOCAT)

(50519, 7)

In [13]:
SOCAT[1]

array([2010.   ,    7.   ,   25.   ,   18.   ,   30.245,  166.806,
        406.4  ])

In [19]:
np.unique(SOCAT[1:,0]) #finds all of the unique values in the first column of the data

array([2010., 2011., 2012., 2014., 2016.])

Let's find all of the indices of the rows that have years 2010 to 2012.

In [21]:
np.argwhere(SOCAT[:,0]==2010.) #here argwhere finds the index of the rows with the year 2010

array([[    1],
       [    2],
       [    3],
       ...,
       [12855],
       [12856],
       [12857]])

In [24]:
bad_years = np.arange(2010.,2013.) #create array of a range of numbers
bad_years

array([2010., 2011., 2012.])

In [32]:
new_SOCAT = np.copy(SOCAT) #create a copy of the SOCAT dataset, this will be the variable we will delete the rows from

In [33]:
for yr in bad_years: #iterate through 2010, 2011, and 2012
    bad_rows = np.argwhere(new_SOCAT[:,0]==yr) #find indices with the given yr
    new_SOCAT = np.delete(new_SOCAT,bad_rows,axis=0) #remove the rows with those indices

In [34]:
np.shape(new_SOCAT) #now we can see new_SOCAT has much fewer rows than SOCAT did

(29753, 7)

In [35]:
np.argwhere(new_SOCAT[:,0]==2012.) #if we try and search for rows with a year we removed, nothing comes up so we know it worked

array([], shape=(0, 1), dtype=int64)